#!/usr/bin/env node
/**
 * Copy DSH ui-theme stylesheets into this package and emit sheets.ts.
 *
 * Usage:
 *   node scripts/sync-theme.mjs
 *   DSH_THEME_SRC=/path/to/ui-theme/src/styles node scripts/sync-theme.mjs
 */
import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const pkgRoot = resolve(here, '..')
const outDir = join(pkgRoot, 'src', 'theme')

const defaultSrc = resolve(
  pkgRoot,
  '../../../../Ops/deepseek-harness/packages/client/ui-theme/src/styles',
)
const srcDir = process.env.DSH_THEME_SRC
  ? resolve(process.env.DSH_THEME_SRC)
  : defaultSrc

const SHEETS = [
  ['base.css', 'BASE_CSS'],
  ['design-platform.css', 'DESIGN_PLATFORM_CSS'],
  ['scrollbar.css', 'SCROLLBAR_CSS'],
  // Shadows, mask blur, markdown font composites — Modal/Menu need these.
  ['gradient-shadow-text.css', 'GRADIENT_SHADOW_TEXT_CSS'],
]

await mkdir(outDir, { recursive: true })

const parts = []
const entries = []
const allParts = []
for (const [file, exportName] of SHEETS) {
  const css = await readFile(join(srcDir, file), 'utf8')
  await copyFile(join(srcDir, file), join(outDir, file))
  parts.push(`export const ${exportName} = ${JSON.stringify(css)}\n`)
  entries.push(`  [${JSON.stringify(file)}, ${exportName}]`)
  allParts.push(css)
}

await writeFile(join(outDir, 'all.css'), allParts.join('\n'))

const sheetsTs = `// AUTO-GENERATED by scripts/sync-theme.mjs — do not edit by hand.
// Source: deepseek-harness packages/client/ui-theme/src/styles

${parts.join('\n')}
export const THEME_SHEETS = [
${entries.join(',\n')},
] as const
`
await writeFile(join(outDir, 'sheets.ts'), sheetsTs)
console.log(`synced ${SHEETS.length} sheets from ${srcDir} → ${outDir}`)
