import { FILE_ICON_SVG } from './file-icons-data'

/**
 * Resolve a file name to its vscode-icons SVG markup.
 *
 * Lookup order: exact special file names (package.json…), well-known
 * prefixes (vite.config.*…), suffixes (.d.ts), then the extension. Anything
 * unrecognized falls back to the generic file icon.
 */
export function fileIconSvg(name: string): string {
  return FILE_ICON_SVG[fileIconKey(name)] ?? FILE_ICON_SVG['default_file'] ?? ''
}

/** Resolve a directory name to its folder icon, open or closed. */
export function folderIconSvg(name: string, open: boolean): string {
  const base = FOLDER_KEYS[name.toLowerCase()]
  const keyed =
    base === undefined
      ? undefined
      : FILE_ICON_SVG[base + (open ? '_opened' : '')] ?? FILE_ICON_SVG[base]
  return (
    keyed ??
    FILE_ICON_SVG[open ? 'default_folder_opened' : 'default_folder'] ??
    ''
  )
}

function fileIconKey(name: string): string {
  const lower = name.toLowerCase()
  const special = SPECIAL_FILE_NAMES[lower]
  if (special !== undefined) return special
  for (const [prefix, key] of SPECIAL_FILE_PREFIXES) {
    if (lower.startsWith(prefix)) return key
  }
  if (lower.endsWith('.d.ts')) return 'file_type_typescriptdef'
  const dot = lower.lastIndexOf('.')
  if (dot <= 0) return 'default_file'
  return EXT_KEYS[lower.slice(dot + 1)] ?? 'default_file'
}

const SPECIAL_FILE_NAMES: Record<string, string> = {
  'package.json': 'file_type_node',
  'package-lock.json': 'file_type_npm',
  '.npmrc': 'file_type_npm',
  'yarn.lock': 'file_type_yarn',
  '.yarnrc': 'file_type_yarn',
  'pnpm-lock.yaml': 'file_type_pnpm',
  'pnpm-workspace.yaml': 'file_type_pnpm',
  'bun.lock': 'file_type_bun',
  'bun.lockb': 'file_type_bun',
  'deno.json': 'file_type_deno',
  'deno.jsonc': 'file_type_deno',
  'composer.json': 'file_type_composer',
  'composer.lock': 'file_type_composer',
  'cargo.toml': 'file_type_cargo',
  'cargo.lock': 'file_type_cargo',
  gemfile: 'file_type_ruby',
  'gemfile.lock': 'file_type_ruby',
  'requirements.txt': 'file_type_pip',
  pipfile: 'file_type_pip',
  'pyproject.toml': 'file_type_poetry',
  'poetry.lock': 'file_type_poetry',
  'go.mod': 'file_type_go',
  'go.sum': 'file_type_go',
  '.gitignore': 'file_type_git',
  '.gitattributes': 'file_type_git',
  '.gitmodules': 'file_type_git',
  '.gitkeep': 'file_type_git',
  dockerfile: 'file_type_docker',
  '.dockerignore': 'file_type_docker',
  '.gitlab-ci.yml': 'file_type_gitlab',
  '.gitlab-ci.yaml': 'file_type_gitlab',
  jenkinsfile: 'file_type_jenkins',
  'cmakelists.txt': 'file_type_cmake',
  makefile: 'file_type_config',
  gnumakefile: 'file_type_config',
  'build.gradle': 'file_type_gradle',
  'settings.gradle': 'file_type_gradle',
  gradlew: 'file_type_gradle',
  'pom.xml': 'file_type_maven',
  '.editorconfig': 'file_type_editorconfig',
  'pubspec.yaml': 'file_type_flutter',
  'nginx.conf': 'file_type_nginx',
  'tauri.conf.json': 'file_type_tauri',
  license: 'file_type_license',
  copying: 'file_type_license',
  readme: 'file_type_markdown',
  changelog: 'file_type_markdown',
}

const SPECIAL_FILE_PREFIXES: ReadonlyArray<readonly [string, string]> = [
  ['tsconfig.', 'file_type_tsconfig'],
  ['vite.config.', 'file_type_vite'],
  ['vitest.config.', 'file_type_vitest'],
  ['webpack.config.', 'file_type_webpack'],
  ['rollup.config.', 'file_type_rollup'],
  ['jest.config.', 'file_type_jest'],
  ['eslint.config.', 'file_type_eslint'],
  ['prettier.config.', 'file_type_prettier'],
  ['babel.config.', 'file_type_babel'],
  ['.eslintrc', 'file_type_eslint'],
  ['.prettierrc', 'file_type_prettier'],
  ['.babelrc', 'file_type_babel'],
  ['.env', 'file_type_dotenv'],
  ['docker-compose.', 'file_type_docker2'],
  ['dockerfile.', 'file_type_docker'],
  ['license.', 'file_type_license'],
  ['readme.', 'file_type_markdown'],
  ['changelog.', 'file_type_markdown'],
]

const EXT_KEYS: Record<string, string> = {
  ts: 'file_type_typescript',
  mts: 'file_type_typescript',
  cts: 'file_type_typescript',
  tsx: 'file_type_reactts',
  js: 'file_type_js',
  mjs: 'file_type_js',
  cjs: 'file_type_js',
  jsx: 'file_type_reactjs',
  json: 'file_type_json',
  jsonc: 'file_type_json',
  json5: 'file_type_json5',
  py: 'file_type_python',
  pyi: 'file_type_python',
  go: 'file_type_go',
  rs: 'file_type_rust',
  java: 'file_type_java',
  kt: 'file_type_kotlin',
  kts: 'file_type_kotlin',
  swift: 'file_type_swift',
  c: 'file_type_c',
  h: 'file_type_cheader',
  cpp: 'file_type_cpp',
  cc: 'file_type_cpp',
  cxx: 'file_type_cpp',
  hpp: 'file_type_cppheader',
  hh: 'file_type_cppheader',
  cs: 'file_type_csharp',
  csproj: 'file_type_csproj',
  sln: 'file_type_sln',
  rb: 'file_type_ruby',
  php: 'file_type_php',
  css: 'file_type_css',
  scss: 'file_type_scss',
  sass: 'file_type_sass',
  less: 'file_type_less',
  html: 'file_type_html',
  htm: 'file_type_html',
  svg: 'file_type_svg',
  xml: 'file_type_xml',
  xsd: 'file_type_xml',
  md: 'file_type_markdown',
  markdown: 'file_type_markdown',
  mdx: 'file_type_mdx',
  sh: 'file_type_shell',
  bash: 'file_type_shell',
  zsh: 'file_type_shell',
  fish: 'file_type_shell',
  ps1: 'file_type_powershell',
  yaml: 'file_type_yaml',
  yml: 'file_type_yaml',
  toml: 'file_type_toml',
  sql: 'file_type_sql',
  vue: 'file_type_vue',
  svelte: 'file_type_svelte',
  dart: 'file_type_dartlang',
  lua: 'file_type_lua',
  r: 'file_type_r',
  jl: 'file_type_julia',
  pl: 'file_type_perl',
  pm: 'file_type_perl',
  groovy: 'file_type_groovy',
  scala: 'file_type_scala',
  clj: 'file_type_clojure',
  cljs: 'file_type_clojure',
  ex: 'file_type_elixir',
  exs: 'file_type_elixir',
  erl: 'file_type_erlang',
  hs: 'file_type_haskell',
  ml: 'file_type_ocaml',
  mli: 'file_type_ocaml',
  zig: 'file_type_zig',
  nim: 'file_type_nim',
  cr: 'file_type_crystal',
  sol: 'file_type_solidity',
  ipynb: 'file_type_jupyter',
  tex: 'file_type_tex',
  wasm: 'file_type_wasm',
  asm: 'file_type_assembly',
  s: 'file_type_assembly',
  graphql: 'file_type_graphql',
  gql: 'file_type_graphql',
  prisma: 'file_type_prisma',
  proto: 'file_type_protobuf',
  coffee: 'file_type_coffeescript',
  pug: 'file_type_pug',
  tf: 'file_type_terraform',
  tfvars: 'file_type_terraform',
  png: 'file_type_image',
  jpg: 'file_type_image',
  jpeg: 'file_type_image',
  gif: 'file_type_image',
  webp: 'file_type_image',
  ico: 'file_type_image',
  bmp: 'file_type_image',
  avif: 'file_type_image',
  woff: 'file_type_font',
  woff2: 'file_type_font',
  ttf: 'file_type_font',
  otf: 'file_type_font',
  eot: 'file_type_font',
  txt: 'file_type_text',
  log: 'file_type_log',
  csv: 'file_type_excel',
  tsv: 'file_type_excel',
  pdf: 'file_type_pdf',
  zip: 'file_type_zip',
  tar: 'file_type_zip',
  gz: 'file_type_zip',
  tgz: 'file_type_zip',
  rar: 'file_type_zip',
  '7z': 'file_type_zip',
  mp3: 'file_type_audio',
  wav: 'file_type_audio',
  ogg: 'file_type_audio',
  flac: 'file_type_audio',
  mp4: 'file_type_video',
  mov: 'file_type_video',
  webm: 'file_type_video',
  avi: 'file_type_video',
  mkv: 'file_type_video',
  xls: 'file_type_excel',
  xlsx: 'file_type_excel',
  doc: 'file_type_word',
  docx: 'file_type_word',
  ppt: 'file_type_powerpoint',
  pptx: 'file_type_powerpoint',
  env: 'file_type_dotenv',
  ini: 'file_type_ini',
  cfg: 'file_type_config',
  conf: 'file_type_config',
  patch: 'file_type_patch',
  diff: 'file_type_diff',
  key: 'file_type_key',
  pem: 'file_type_key',
  crt: 'file_type_cert',
  cer: 'file_type_cert',
  sqlite: 'file_type_sqlite',
  sqlite3: 'file_type_sqlite',
  db: 'file_type_sqlite',
  bin: 'file_type_binary',
  exe: 'file_type_binary',
  dll: 'file_type_binary',
}

const FOLDER_KEYS: Record<string, string> = {
  src: 'folder_type_src',
  test: 'folder_type_test',
  tests: 'folder_type_test',
  __tests__: 'folder_type_test',
  spec: 'folder_type_test',
  node_modules: 'folder_type_node',
  dist: 'folder_type_dist',
  build: 'folder_type_dist',
  out: 'folder_type_dist',
  docs: 'folder_type_docs',
  doc: 'folder_type_docs',
  images: 'folder_type_images',
  img: 'folder_type_images',
  assets: 'folder_type_images',
  '.git': 'folder_type_git',
  '.github': 'folder_type_github',
  public: 'folder_type_public',
  components: 'folder_type_component',
  component: 'folder_type_component',
  config: 'folder_type_config',
  '.config': 'folder_type_config',
  client: 'folder_type_client',
  server: 'folder_type_server',
  views: 'folder_type_view',
  view: 'folder_type_view',
  plugins: 'folder_type_plugin',
  plugin: 'folder_type_plugin',
}
